### PR TITLE
add prettier config file for issue #159

### LINKED ISSUE #159: [FEATURE] request add prettier config file
### What is the new or updated feature that you are suggesting?

Nowadays everyone uses [Prettier](https://prettier.io/), An opinionated code formatter.

The issue is everyone have different global settings of prettier according to their style. but this can cause useless changes to opensource projects as many people works on same code.

So having a `prettier config file` inside project directory can resolve this issue.

### How to solve this issue/ add this featuer?

adding a file `.prettierrc` and `.prettierignore` will solve this issue

### PR DESCRIPTION
**Pull request by RohitSaini7**
## 🛠️ Fixes Issue
Close #159.

## 👨‍💻 Changes proposed
- add `.prettierrc.json` file
- add `.prettierignore` file
- ran prettier for every file so that others don't have to face unknown changes for no reasons.

## ✔️ Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
If you are not convinced enough to merge this PR, please read these articles:
- [why you need .prettierrc file](https://www.youtube.com/watch?v=Nvc0fWg4DbQ)
- [Prettier + Format On Save = Never worry about formatting JavaScript again](https://scottsauber.com/2017/06/10/prettier-format-on-save-never-worry-about-formatting-javascript-again/)
- [Snippet. My full Prettier (.prettierrc) config file](https://www.boag.online/blog/full-prettier-prettierrc-config)

### CODE REVIEW

**Comment by ingressive4good** [comment]
@RohitSaini7 fix your merge conflict

**Comment by RohitSaini7** [comment]
> 

done

**Comment by t-bello7** [comment]
@RohitSaini7  Can you kindly fix the linter, prettier issue to avoid breaking the deployment process.

**Comment by RohitSaini7** [comment]
Re raised PR #181.

**Pull request closed without merging**
