### PR TITLE
Admin Dashboard

### LINKED ISSUE #166: Admin: Dashboard
Title
Develop the Admin Dashboard Pages

## Summary

- Develop the  11 pages
- This issue is for an experience developer that really understand how to interpret and develop the designs

## Additional information

- Send a pull request for each of the pages
- Ensure you look through the code base for usable components to avoid duplicates.
- Check the user dashboard components for some useable component
- Follow the existing file structure
- This issue is dependent on issue #163 ensure the issue is closed first to make your work easier

### PR DESCRIPTION
**Pull request by Osilaja78**
## 🛠️ Fixes Issue

Closes #166 

## 👨‍💻 Changes proposed

Developed all 11 pages of admin dashboard
Mobile responsive

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Added a new dependency "recharts" to handle the chart on the admin dashboard page
## 📷 Screenshots

### CODE REVIEW

**Comment by Osilaja78** [comment]
New PR @dprincecoder @t-bello7 @ingressive4good

**Review by dprincecoder — DISMISSED** [review]
good to merge

**Comment by ingressive4good** [comment]
Please, fix your conflicts

**Comment by Osilaja78** [comment]
Done @ingressive4good

**Pull request merged**
