### PR TITLE
developed the entire landing page excluding the footer

### LINKED ISSUE #2: Navbar, Hero and Section Component of Landing Page
- Develop the home page UI appropriately
- Ensure they are responsive and follow the responsive design on the figma
- Implement images properly
- Follow the color guide and the appropriate colors

### PR DESCRIPTION
**Pull request by CyberGeni**
## 🛠️ Fixes Issue

closes #2 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by ingressive4good** [comment]
@CyberGeni  the navigation are not working when it's on mobile view and the footer is also not includes

**Comment by CyberGeni** [comment]
@ingressive4good i've fixed it, it works now. the footer was detached to a standalone issue

**Comment by CyberGeni** [comment]
i don't know why, but the images aren't showing on the netlify preview, so the hamburger menu can't be clicked. i'll see if i can look into why it isn't displaying

**Comment by ingressive4good** [comment]
@CyberGeni kindly resolve your conflict to allow merging of your PR

**Comment by CyberGeni** [comment]
@ingressive4good i've resolved the merge conflict

**Comment by ingressive4good** [comment]
@CyberGeni Please fix the conflict on your PR

**Comment by CyberGeni** [comment]
@ingressive4good fixed merge conflict, again

**Pull request merged**
