### PR TITLE
Delete uploaded product dashboard

### LINKED ISSUE #20: User-Dashboard: Products (Delete uploaded products)
- Develop the User Dashboard delete uploaded product pages UI appropriately
- The user dashboard upload product page contains 4 pages ( you should send a pull request for each of the pages)
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

### PR DESCRIPTION
**Pull request by zakariyahrobiat**
## 🛠️ Fixes Issue
Closes #20 

## 👨‍💻 Changes proposed
Screenshot (14)

## ✔️ Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Screenshot (21)

## 📷 Screenshots

### CODE REVIEW

**Comment by zakariyahrobiat** [comment]
@t-bello7 @dprincecoder

**Review by dprincecoder — APPROVED** [review]
Good to merge

**Comment by t-bello7** [comment]
Screenshot from 2022-10-23 11-04-06
The homepage is blank

**Comment by zakariyahrobiat** [comment]
@t-bello7 you didn't add the suffix "delete-product-dashboard"

**Comment by zakariyahrobiat** [comment]
Okay
I will fixed that

**Pull request merged**
