### PR TITLE
add-success-and-edit-pop-up-message

### PR DESCRIPTION
**Pull request by zakariyahrobiat**
## 🛠️ Fixes Issue
closes #145

## 👨‍💻 Changes proposed
add and edit pop up
add a success message
add mark as available message

## ✔️ Check List (Check all the applicable boxes) 

- [X ] My code follows the code style of this project.
- [X ] This PR does not contain plagiarized content.
- [X ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (7)
Screenshot (5)
Screenshot (6)

### CODE REVIEW

**Comment by dprincecoder** [comment]
You have your parent folder name “delete” I strongly recommend you rename it what is actually deleting 
E.g deleteProducts

**Comment by zakariyahrobiat** [comment]
@dprincecoder done

**Comment by dprincecoder** [comment]
@zakariyahrobiat i don’t see a change oh 
Did you push your changes at all ?

**Comment by zakariyahrobiat** [comment]
There are changes OOO
When you click on the three dots, mark as available will change the unavailable to available and there will be success message

**Comment by dprincecoder** [comment]
Ok 
this PR is ready to be merged

**Pull request merged**
