### PR TITLE
delete product

### PR DESCRIPTION
**Pull request by zakariyahrobiat**
## 🛠️ Fixes Issue
closes #81

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (3)
Screenshot (2)

Screenshot (4)

### CODE REVIEW

**Comment by ingressive4good** [comment]
@zakariyahrobiat please resolve your conflict to allow merging of your PR

**Comment by zakariyahrobiat** [comment]
@ingressive4good  it has been resolved

**Comment by ingressive4good** [comment]
hello! @zakariyahrobiat please fix the conflict on your PR

**Comment by zakariyahrobiat** [comment]
@ingressive4good PR conflict has been fixed

**Review by t-bello7 — COMMENTED** [review]
Amazing Job @zakariyahrobiat. However, your files are all scattered which is really hard to understand what your code is trying to solve. Moving further we would follow this style and file structure guideline in the project - https://andela.com/insights/structuring-your-react-application-atomic-design-principles/
P.S - It's my first time learning about but it's an opportunity to learn and a step into being a senior developer.
Also, you did not have to put a screenshot of your developed components in the public folder. If your component is well connected in the routing. You can view it on https://[yourprdeployedlink]/[yourroutname]

**Comment by zakariyahrobiat** [comment]
@dprincecoder @t-bello7 done

**Comment by zakariyahrobiat** [comment]
@dprincecoder @t-bello7 fixed

**Comment by dprincecoder** [comment]
### Do this to resolve the conflicts
 file can’t be merged right now
Why:
You have a conflicts to resolve.
proTip: To resolve, first if you forked the repo then sync it with i4g repo so everything is up to date
Second: checkout to the develop branch and do git pull.
third: checkout to a new branch called resolve conflicts, then if you can copy the code you already did in old branch that conflicts then do else you can code afresh, when done, checkout to this branch that has conflicts then merge this new branch called resolve conflicts you created earlier then you can now see all conflicting files to resolve it.
To make it simple in vscode open all files showing the conflicts then hovering on them will ask you to either accept incoming changes, keep both Changes or compare changes, here click on accept incoming changes after all this, you will see a button that say mark as resolve click it, do so in all conflicting files, you should be good, then commit your changes

**Comment by dprincecoder** [comment]
Looks good to merge

**Pull request merged**
