### PR TITLE
Create Account UI

### LINKED ISSUE #3: Authentication: Create Account-UI
- Develop the create account UI appropriately
- Ensure they are responsive and follow the responsive design on the figma
- Implement images properly
- Follow the color guide and the appropriate colors

### PR DESCRIPTION
**Pull request by Mudi-Igbinoba**
## 🛠️ Fixes Issue
Closes #3 

## 👨‍💻 Changes proposed

- Developed authentication: create account ui.
- All pages.
- Mobile responsive

## ✔️ Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Endpoints
- /create-account

## 📷 Screenshots
create-account-desktop

create-account-ipad

create-account-mobile

### CODE REVIEW

**Comment by dprincecoder** [comment]
Ready to merge

**Comment by t-bello7** [comment]
Amazing Job. Can't wait to have this merged. Kindly just add a nav link to the create account page on the landing page and also resolve the conflicts.

**Comment by Mudi-Igbinoba** [comment]
> Amazing Job. Can't wait to have this merged. Kindly just add a nav link to the create account page on the landing page and also resolve the conflicts.

Done @t-bello7

**Comment by dprincecoder** [comment]
Ready to merge

**Comment by t-bello7** [comment]
Alright, It's good to merge.

**Pull request merged**
