### PR TITLE
moved help page to pages directory

### LINKED ISSUE #21: User-Dashboard: Wishlist(View product on wishlist)
- Develop the User Dashboard wishlist pages UI appropriately
- The user dashboard upload product page contains 3 pages ( you should send a pull request for each of the pages)
- Ensure they are responsive and follow the responsive design on the Figma
- Implement images properly
- Follow the colour guide and the appropriate colours

### PR DESCRIPTION
**Pull request by Shegun-istaken**
## 👨‍💻 Changes proposed

- Moved the Help and Support Page file to the pages directory for easy identification. Previously, it was in the molecules folder, but a pages folder has been created now, so that's a better place for it,

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Endpoints
- /wishlist (view products in wishlist)
- /add-to-wishlist (add products to wishlist)

## 📷 Screenshots

<br/>

<br/>

### CODE REVIEW

**Comment by ingressive4good** [comment]
hello! @Shegun-istaken please fix the conflict on your PR

**Comment by Shegun-istaken** [comment]
> hello! @Shegun-istaken please fix the conflict on your PR

They have been resolved

**Comment by ingressive4good** [comment]
there is a conflict

**Comment by Shegun-istaken** [comment]
> there is a conflict

I just resolved them again.

**Review by t-bello7 — COMMENTED** [review]
This is good to merge.

**Pull request merged**
