### PR TITLE
Enhance and optimise the authentication page

### LINKED ISSUE #205: Enhance and Optimise the Authentication Page
- Enhance and optimise the images on the the authentications pages and ensure they are displayed properly
- Add links to buttons and Navigation bar
- add the updated content
- Develop the remaining part of the Authentication pages that has not been developed
- Ensure the overall Authentication pages meet the design standard

### PR DESCRIPTION
**Pull request by ScottDeev**
## 🛠️ Fixes Issue
`Closes #205`

## 👨‍💻 Changes proposed

1. Fixed authentication issues with image and icons display
2. Linked the Mobile navbar to all authentication pages
3. Added success pop ups to authentication pages that did not have
4. Added the hide and show functionality to some password inputs in some authentication pages
5. Added redirecting paths to buttons and links like login, forgot password and create an account links
6. Adjusted the styling to have the same format with the figma design
7. Created the forgot password page since I couldn't see it in the pages folder

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by t-bello7** [comment]
Screenshot_2022-10-22-07-00-07-477_com android chrome
Hey @ScottDeev, Nice work optimizing the unprotected pages which are the homepage,login,createaccount,kyc, support, e.t.c.However you added the dashboard navigation which is for authenticated users.

Screenshot_2022-10-22-07-03-26-445_com android chrome

 👆 This should be the navigation on this pages. 
- The link to the forgot password is broken 
- The footer links to support and kyc is also broken

**Comment by ScottDeev** [comment]
I was thinking the issue was strictly for the pages found in the authentication section of the figma design. Because the support, home page are not there. I will try and fix the broken footer of those two pages

**Comment by ScottDeev** [comment]
> Screenshot_2022-10-22-07-00-07-477_com android chrome Hey @ScottDeev, Nice work optimizing the unprotected pages which are the homepage,login,createaccount,kyc, support, e.t.c.However you added the dashboard navigation which is for authenticated users.
> 
> Screenshot_2022-10-22-07-03-26-445_com android chrome
> 
> 👆 This should be the navigation on this pages.
> 
> * The link to the forgot password is broken
> * The footer links to support and kyc is also broken

Oh. I see now. That was a big mix up from me. I will correct the navigation

**Comment by ScottDeev** [comment]
@t-bello7 I have been able to make the necessary corrections. You can help review again.

**Comment by t-bello7** [comment]
@ScottDeev Good to merge.

**Comment by ingressive4good** [comment]
@ScottDeev please fix the conflicts, i should have merge this first

**Comment by ScottDeev** [comment]
> @ScottDeev please fix the conflicts, i should have merge this first

Done @ingressive4good

**Pull request merged**
