### PR TITLE
Mobile Nav Bar for Admin

### LINKED ISSUE #187: Design of Side Navigation for Admin Dashboard - Mobile
- Design the side navigation for the admin dashboard (mobile view) to allow for easy navigation through the whole interface.

### PR DESCRIPTION
**Pull request by FrankUkay**
Worked on the Mobile Nav Bar for Admin
Close #187 

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by De-mi-de — DISMISSED** [review]
well done
good to merge

**Review by nhorah — DISMISSED** [review]
well done
good to merge

**Review by De-mi-de — APPROVED** [review]
well done
good to merge

**Review by nhorah — APPROVED** [review]
well done
good to merge

**Pull request merged**
