### PR TITLE
messages-chat-interface

### LINKED ISSUE #164: Admin: Messages
Title
Develop the Admin Message Pages

## Summary

Develop the  3 Message pages
- Admin Message page 1
- Admin Message page  2
- Admin Message page 3

## Additional information

- Send a pull request for each of the pages
- Ensure you look through the codebase for usable components to avoid duplicates.
- Check the user Message components for some useable component
- Follow the existing file structure

### PR DESCRIPTION
**Pull request by Shegun-istaken**
## 🛠️ Fixes Issue 

This PR closes #164 
To see this page, use "admin/messages/chat"

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by Onyelaudochukwuka** [comment]
Can you add a lintk to connect the message start page to the message chat page

**Comment by Shegun-istaken** [comment]
> Can you add a lintk to connect the message start page to the message chat page

Done.

**Comment by Onyelaudochukwuka** [comment]
Great work 
But can you fix the part labelled they're a bit different from the design.

Screen Shot 2022-10-21 at 11 17 45 AM

**Comment by dprincecoder** [comment]
Good to merge

**Comment by Onyelaudochukwuka** [comment]
> Good to merge

Gimme a sec to check it out

**Pull request merged**
