### PR TITLE
Dashboard: notification integration started

### PR DESCRIPTION
**Pull request by maziigwe**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by ingressive4good** [comment]
@maziigwe please fix the conflict

**Comment by maziigwe** [comment]
Please I can't find the cause of the conflict for now. Any relevant tip will be appreciated. Thank you!

**Comment by dprincecoder** [comment]
Someone has installed a module in their branch, that updated the yarn.lock file, so just pull develop branch then fix the conflicts, you can watch my video on how to resolve conflicts check the video in the Telegram chat group

**Comment by maziigwe** [comment]
I have pulled the latest changes yet, deploy is still failing. However, all is working on my development environment.

**Pull request closed without merging**
