### PR TITLE
 admin users profile page (without products)

### PR DESCRIPTION
**Pull request by Mudi-Igbinoba**
## 🛠️ Fixes Issue
Fixes one of the pages listed in #173 

## 👨‍💻 Changes proposed
- Added the Admin Users Profile Page(without products)
- Added the route `admin/users/profile`

## ✔️ Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
To see changes, follow route `admin/users/profile`

## 📷 Screenshots
- Desktop view
download

- Ipad view
download

- Mobile view
download

### CODE REVIEW

**Comment by Mudi-Igbinoba** [comment]
@t-bello7 and @dprincecoder please review

**Review by t-bello7 — COMMENTED** [review]
@Mudi-Igbinoba This is one of the clean Prs. But I think you have made changes to the routes.jsx file causing breaks.
 
Screenshot from 2022-10-18 22-07-03
The route to the /admin/profile comes up blank

**Comment by dprincecoder** [comment]
Nice good to merge

**Comment by Mudi-Igbinoba** [comment]
> @Mudi-Igbinoba This is one of the clean Prs. But I think you have made changes to the routes.jsx file causing breaks.
> 
> Screenshot from 2022-10-18 22-07-03 The route to the /admin/profile comes up blank

@t-bello7 It's admin/users/profile

**Pull request merged**
