### PR TITLE
Forget Password UI

### PR DESCRIPTION
**Pull request by dprincecoder**
## 🛠️ Fixes Issue

This PR will close issue #10 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by dprincecoder** [comment]
All Good ready to merge

**Comment by ingressive4good** [comment]
there is a conflict

**Comment by dprincecoder** [comment]
Ohh someone PR has been merge and changed stuff again, I will fix the conflicts and request for immediate merge

**Comment by dprincecoder** [comment]
@ingressive4good and @dabsclement this PR is ready for merge, please merge it before merging others, so other conflicts don't arise

**Pull request merged**
